// Generated by tools/generate-contracts.mjs. DO NOT EDIT.
export type NativeMemoryResult = SessionMetadata | SessionRead | SessionList | SessionCreated;
export type Identifier = string;

export interface SessionMetadata {
  schema_version: 1;
  id: Identifier;
  kind: "session";
  title: string;
  source_id: Identifier;
  review_status: "unreviewed";
  created_at: string;
}
export interface SessionRead {
  metadata: SessionMetadata;
  body: string;
  source_text: string;
}
export interface SessionList {
  /**
   * @maxItems 50
   */
  items: SessionMetadata[];
  total: number;
  next_offset: number | null;
}
export interface SessionCreated {
  id: Identifier;
}
