// Generated by tools/generate-contracts.mjs. DO NOT EDIT.
export type NativeMemoryResult =
  | SessionMetadata
  | SessionRead
  | SessionList
  | SessionCreated
  | MemoryAnswer
  | VaultStatus
  | AiPreviewRequest
  | AiPreviewResult
  | AiPrompt
  | AiDiscardResult
  | CaptureStatus
  | CaptureIndexResult
  | CaptureImportResult
  | CaptureHookStatus
  | CaptureRecoveryResult
  | CaptureHistoryPreview
  | CaptureHistoryImportResult
  | CaptureCleanupResult;
export type Identifier = string;
export type AiModel = string;
export type AiCap = number;
export type AiIdentifier = string;
export type AiHash = string;
export type AiProviderRequest =
  | {
      provider: "openai";
      endpoint: "https://api.openai.com/v1/responses";
      headers: {
        "Content-Type": "application/json";
      };
      body: {
        model: AiModel;
        instructions: string;
        input: AiMessage;
        max_output_tokens: AiCap;
        store: false;
        stream: false;
      };
    }
  | {
      provider: "anthropic";
      endpoint: "https://api.anthropic.com/v1/messages";
      headers: {
        "Content-Type": "application/json";
        "anthropic-version": "2023-06-01";
      };
      body: {
        model: AiModel;
        system: string;
        messages: AiMessage;
        max_tokens: AiCap;
        stream: false;
      };
    };
/**
 * @minItems 1
 * @maxItems 1
 */
export type AiMessage = [
  {
    role: "user";
    content: string;
  }
];

export interface SessionMetadata {
  schema_version: 1;
  id: Identifier;
  kind: "session";
  title: string;
  source_id: Identifier;
  review_status: "unreviewed";
  source_kind?: "hook_capture";
  provider?: "claude-code" | "codex";
  created_at: string;
}
export interface SessionRead {
  metadata: SessionMetadata;
  body: string;
  source_text: string;
}
export interface SessionList {
  /**
   * @maxItems 50
   */
  items: SessionMetadata[];
  total: number;
  next_offset: number | null;
}
export interface SessionCreated {
  id: Identifier;
}
export interface MemoryAnswer {
  schema_version: 1;
  status: "answered" | "insufficient_evidence";
  answer: string;
  /**
   * @maxItems 5
   */
  sources: MemoryAnswerSource[];
}
export interface MemoryAnswerSource {
  session_id: Identifier;
  title: string;
  quote: string;
  start: number;
  end: number;
  snapshot_sha256: string;
  provider?: "claude-code" | "codex";
}
export interface VaultStatus {
  connected: boolean;
  ai_enabled: false;
}
export interface AiPreviewRequest {
  provider: "openai" | "anthropic";
  model: AiModel;
  question: string;
  max_output_tokens: AiCap;
  /**
   * @minItems 1
   * @maxItems 1
   */
  selections: [
    {
      kind: "session";
      id: AiIdentifier;
      start: number;
      end: number;
    }
  ];
}
export interface AiPreviewResult {
  preview_id: AiIdentifier;
  payload_sha256: AiHash;
  expires_in_seconds: 300;
  can_send: false;
  sharing_warning: string;
  request: AiProviderRequest;
  /**
   * @minItems 1
   * @maxItems 1
   */
  local_references: [
    {
      kind: "session";
      id: AiIdentifier;
      start: number;
      end: number;
      source_id: "S1";
      snapshot_sha256: AiHash;
    }
  ];
}
export interface AiPrompt {
  question: string;
  /**
   * @minItems 1
   * @maxItems 5
   */
  sources: [
    {
      source_id: string;
      text: string;
    },
    ...{
      source_id: string;
      text: string;
    }[]
  ];
}
export interface AiDiscardResult {
  discarded: true;
}
export interface CaptureStatus {
  schema_version: 1;
  inbox_root: string;
  health: CaptureHealth;
  /**
   * @minItems 2
   * @maxItems 2
   */
  clients: [CaptureClient, CaptureClient];
}
export interface CaptureHealth {
  schema_version: 1;
  kind: "capture_health";
  derived: true;
  bytes_used: number;
  quota_bytes: 1073741824;
  failures: number;
  pending_spool: number;
  retention_days: 30;
  last_indexed_at: string | null;
}
export interface CaptureClient {
  provider: "claude-code" | "codex";
  configured: boolean;
  enabled: boolean;
  memory_enabled: boolean;
  source_root: string;
  /**
   * @maxItems 32
   */
  memory_roots: string[];
  revision: string;
  snippet: string;
}
export interface CaptureIndexResult {
  status: "indexed";
  sessions: number;
  memories: number;
  revisions: number;
}
export interface CaptureImportResult {
  schema_version: 1;
  created: number;
  updated: number;
  unchanged: number;
  acknowledged: number;
  skipped: number;
  memories_pending: number;
  next_offset: number | null;
}
export interface CaptureHookStatus {
  status: "installed" | "absent" | "partial";
  config_path: string;
  trust_verified: false;
}
export interface CaptureRecoveryResult {
  restored: number;
  unchanged: number;
  skipped: number;
}
export interface CaptureHistoryPreview {
  preview_id: string;
  source_root: string;
  sessions: number;
  files: number;
  bytes: number;
  skipped: number;
  earliest: string | null;
  latest: string | null;
}
export interface CaptureHistoryImportResult {
  captured: number;
  skipped: number;
  next_offset: number | null;
}
export interface CaptureCleanupResult {
  removed_revisions: number;
  removed_chunks: number;
  bytes_freed: number;
  deferred: boolean;
}
