// Generated by tools/generate-contracts.mjs. DO NOT EDIT.
export type NativeMemoryResult =
  | SessionMetadata
  | SessionRead
  | SessionList
  | SessionCreated
  | VaultStatus
  | AiPreviewRequest
  | AiPreviewResult
  | AiPrompt
  | AiDiscardResult;
export type Identifier = string;
export type AiModel = string;
export type AiCap = number;
export type AiIdentifier = string;
export type AiHash = string;
export type AiProviderRequest =
  | {
      provider: "openai";
      endpoint: "https://api.openai.com/v1/responses";
      headers: {
        "Content-Type": "application/json";
      };
      body: {
        model: AiModel;
        instructions: string;
        input: AiMessage;
        max_output_tokens: AiCap;
        store: false;
        stream: false;
      };
    }
  | {
      provider: "anthropic";
      endpoint: "https://api.anthropic.com/v1/messages";
      headers: {
        "Content-Type": "application/json";
        "anthropic-version": "2023-06-01";
      };
      body: {
        model: AiModel;
        system: string;
        messages: AiMessage;
        max_tokens: AiCap;
        stream: false;
      };
    };
/**
 * @minItems 1
 * @maxItems 1
 */
export type AiMessage = [
  {
    role: "user";
    content: string;
  }
];

export interface SessionMetadata {
  schema_version: 1;
  id: Identifier;
  kind: "session";
  title: string;
  source_id: Identifier;
  review_status: "unreviewed";
  created_at: string;
}
export interface SessionRead {
  metadata: SessionMetadata;
  body: string;
  source_text: string;
}
export interface SessionList {
  /**
   * @maxItems 50
   */
  items: SessionMetadata[];
  total: number;
  next_offset: number | null;
}
export interface SessionCreated {
  id: Identifier;
}
export interface VaultStatus {
  connected: boolean;
  ai_enabled: false;
}
export interface AiPreviewRequest {
  provider: "openai" | "anthropic";
  model: AiModel;
  question: string;
  max_output_tokens: AiCap;
  /**
   * @minItems 1
   * @maxItems 1
   */
  selections: [
    {
      kind: "session";
      id: AiIdentifier;
      start: number;
      end: number;
    }
  ];
}
export interface AiPreviewResult {
  preview_id: AiIdentifier;
  payload_sha256: AiHash;
  expires_in_seconds: 300;
  can_send: false;
  sharing_warning: string;
  request: AiProviderRequest;
  /**
   * @minItems 1
   * @maxItems 1
   */
  local_references: [
    {
      kind: "session";
      id: AiIdentifier;
      start: number;
      end: number;
      source_id: "S1";
      snapshot_sha256: AiHash;
    }
  ];
}
export interface AiPrompt {
  question: string;
  /**
   * @minItems 1
   * @maxItems 5
   */
  sources: [
    {
      source_id: string;
      text: string;
    },
    ...{
      source_id: string;
      text: string;
    }[]
  ];
}
export interface AiDiscardResult {
  discarded: true;
}
