// Generated by tools/generate-contracts.mjs. DO NOT EDIT.
// @ts-nocheck -- generated standalone JavaScript validators.
import * as runtime0 from 'ajv/dist/runtime/ucs2length.js';
import * as runtime1 from 'ajv-formats/dist/formats.js';
('use strict');
export const validateSessionMetadata = validate21;
const schema32 = {
  title: 'SessionMetadata',
  type: 'object',
  properties: {
    schema_version: { const: 1 },
    id: { $ref: '#/$defs/Identifier' },
    kind: { const: 'session' },
    title: { type: 'string', minLength: 1, maxLength: 200 },
    source_id: { $ref: '#/$defs/Identifier' },
    review_status: { const: 'unreviewed' },
    created_at: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?!0000)[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]{1,6})?Z$',
    },
  },
  required: [
    'schema_version',
    'id',
    'kind',
    'title',
    'source_id',
    'review_status',
    'created_at',
  ],
  additionalProperties: false,
};
const schema33 = {
  type: 'string',
  pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
};
const pattern4 = new RegExp(
  '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
  'u',
);
const pattern6 = new RegExp(
  '^(?!0000)[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]{1,6})?Z$',
  'u',
);
const func1 = {
  default:
    typeof runtime0.default === 'function'
      ? runtime0.default
      : runtime0.default.default,
}.default;
const formats0 = runtime1.fullFormats['date-time'];
function validate21(
  data,
  {
    instancePath = '',
    parentData,
    parentDataProperty,
    rootData = data,
    dynamicAnchors = {},
  } = {},
) {
  let vErrors = null;
  let errors = 0;
  const evaluated0 = validate21.evaluated;
  if (evaluated0.dynamicProps) {
    evaluated0.props = undefined;
  }
  if (evaluated0.dynamicItems) {
    evaluated0.items = undefined;
  }
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0;
      if (
        (data.schema_version === undefined && (missing0 = 'schema_version')) ||
        (data.id === undefined && (missing0 = 'id')) ||
        (data.kind === undefined && (missing0 = 'kind')) ||
        (data.title === undefined && (missing0 = 'title')) ||
        (data.source_id === undefined && (missing0 = 'source_id')) ||
        (data.review_status === undefined && (missing0 = 'review_status')) ||
        (data.created_at === undefined && (missing0 = 'created_at'))
      ) {
        validate21.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ];
        return false;
      } else {
        const _errs1 = errors;
        for (const key0 in data) {
          if (
            !(
              key0 === 'schema_version' ||
              key0 === 'id' ||
              key0 === 'kind' ||
              key0 === 'title' ||
              key0 === 'source_id' ||
              key0 === 'review_status' ||
              key0 === 'created_at'
            )
          ) {
            validate21.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ];
            return false;
            break;
          }
        }
        if (_errs1 === errors) {
          if (data.schema_version !== undefined) {
            const _errs2 = errors;
            if (1 !== data.schema_version) {
              validate21.errors = [
                {
                  instancePath: instancePath + '/schema_version',
                  schemaPath: '#/properties/schema_version/const',
                  keyword: 'const',
                  params: { allowedValue: 1 },
                  message: 'must be equal to constant',
                },
              ];
              return false;
            }
            var valid0 = _errs2 === errors;
          } else {
            var valid0 = true;
          }
          if (valid0) {
            if (data.id !== undefined) {
              let data1 = data.id;
              const _errs3 = errors;
              const _errs4 = errors;
              if (errors === _errs4) {
                if (typeof data1 === 'string') {
                  if (!pattern4.test(data1)) {
                    validate21.errors = [
                      {
                        instancePath: instancePath + '/id',
                        schemaPath: '#/$defs/Identifier/pattern',
                        keyword: 'pattern',
                        params: {
                          pattern:
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
                        },
                        message:
                          'must match pattern "' +
                          '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' +
                          '"',
                      },
                    ];
                    return false;
                  }
                } else {
                  validate21.errors = [
                    {
                      instancePath: instancePath + '/id',
                      schemaPath: '#/$defs/Identifier/type',
                      keyword: 'type',
                      params: { type: 'string' },
                      message: 'must be string',
                    },
                  ];
                  return false;
                }
              }
              var valid0 = _errs3 === errors;
            } else {
              var valid0 = true;
            }
            if (valid0) {
              if (data.kind !== undefined) {
                const _errs6 = errors;
                if ('session' !== data.kind) {
                  validate21.errors = [
                    {
                      instancePath: instancePath + '/kind',
                      schemaPath: '#/properties/kind/const',
                      keyword: 'const',
                      params: { allowedValue: 'session' },
                      message: 'must be equal to constant',
                    },
                  ];
                  return false;
                }
                var valid0 = _errs6 === errors;
              } else {
                var valid0 = true;
              }
              if (valid0) {
                if (data.title !== undefined) {
                  let data3 = data.title;
                  const _errs7 = errors;
                  if (errors === _errs7) {
                    if (typeof data3 === 'string') {
                      if (func1(data3) > 200) {
                        validate21.errors = [
                          {
                            instancePath: instancePath + '/title',
                            schemaPath: '#/properties/title/maxLength',
                            keyword: 'maxLength',
                            params: { limit: 200 },
                            message: 'must NOT have more than 200 characters',
                          },
                        ];
                        return false;
                      } else {
                        if (func1(data3) < 1) {
                          validate21.errors = [
                            {
                              instancePath: instancePath + '/title',
                              schemaPath: '#/properties/title/minLength',
                              keyword: 'minLength',
                              params: { limit: 1 },
                              message: 'must NOT have fewer than 1 characters',
                            },
                          ];
                          return false;
                        }
                      }
                    } else {
                      validate21.errors = [
                        {
                          instancePath: instancePath + '/title',
                          schemaPath: '#/properties/title/type',
                          keyword: 'type',
                          params: { type: 'string' },
                          message: 'must be string',
                        },
                      ];
                      return false;
                    }
                  }
                  var valid0 = _errs7 === errors;
                } else {
                  var valid0 = true;
                }
                if (valid0) {
                  if (data.source_id !== undefined) {
                    let data4 = data.source_id;
                    const _errs9 = errors;
                    const _errs10 = errors;
                    if (errors === _errs10) {
                      if (typeof data4 === 'string') {
                        if (!pattern4.test(data4)) {
                          validate21.errors = [
                            {
                              instancePath: instancePath + '/source_id',
                              schemaPath: '#/$defs/Identifier/pattern',
                              keyword: 'pattern',
                              params: {
                                pattern:
                                  '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
                              },
                              message:
                                'must match pattern "' +
                                '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' +
                                '"',
                            },
                          ];
                          return false;
                        }
                      } else {
                        validate21.errors = [
                          {
                            instancePath: instancePath + '/source_id',
                            schemaPath: '#/$defs/Identifier/type',
                            keyword: 'type',
                            params: { type: 'string' },
                            message: 'must be string',
                          },
                        ];
                        return false;
                      }
                    }
                    var valid0 = _errs9 === errors;
                  } else {
                    var valid0 = true;
                  }
                  if (valid0) {
                    if (data.review_status !== undefined) {
                      const _errs12 = errors;
                      if ('unreviewed' !== data.review_status) {
                        validate21.errors = [
                          {
                            instancePath: instancePath + '/review_status',
                            schemaPath: '#/properties/review_status/const',
                            keyword: 'const',
                            params: { allowedValue: 'unreviewed' },
                            message: 'must be equal to constant',
                          },
                        ];
                        return false;
                      }
                      var valid0 = _errs12 === errors;
                    } else {
                      var valid0 = true;
                    }
                    if (valid0) {
                      if (data.created_at !== undefined) {
                        let data6 = data.created_at;
                        const _errs13 = errors;
                        if (errors === _errs13) {
                          if (errors === _errs13) {
                            if (typeof data6 === 'string') {
                              if (!pattern6.test(data6)) {
                                validate21.errors = [
                                  {
                                    instancePath: instancePath + '/created_at',
                                    schemaPath:
                                      '#/properties/created_at/pattern',
                                    keyword: 'pattern',
                                    params: {
                                      pattern:
                                        '^(?!0000)[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]{1,6})?Z$',
                                    },
                                    message:
                                      'must match pattern "' +
                                      '^(?!0000)[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]{1,6})?Z$' +
                                      '"',
                                  },
                                ];
                                return false;
                              } else {
                                if (!formats0.validate(data6)) {
                                  validate21.errors = [
                                    {
                                      instancePath:
                                        instancePath + '/created_at',
                                      schemaPath:
                                        '#/properties/created_at/format',
                                      keyword: 'format',
                                      params: { format: 'date-time' },
                                      message:
                                        'must match format "' +
                                        'date-time' +
                                        '"',
                                    },
                                  ];
                                  return false;
                                }
                              }
                            } else {
                              validate21.errors = [
                                {
                                  instancePath: instancePath + '/created_at',
                                  schemaPath: '#/properties/created_at/type',
                                  keyword: 'type',
                                  params: { type: 'string' },
                                  message: 'must be string',
                                },
                              ];
                              return false;
                            }
                          }
                        }
                        var valid0 = _errs13 === errors;
                      } else {
                        var valid0 = true;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      validate21.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ];
      return false;
    }
  }
  validate21.errors = vErrors;
  return errors === 0;
}
validate21.evaluated = {
  props: true,
  dynamicProps: false,
  dynamicItems: false,
};
export const validateSessionRead = validate22;
const schema35 = {
  title: 'SessionRead',
  type: 'object',
  properties: {
    metadata: { $ref: '#/$defs/SessionMetadata' },
    body: { type: 'string', maxLength: 32768 },
    source_text: { type: 'string', maxLength: 65536 },
  },
  required: ['metadata', 'body', 'source_text'],
  additionalProperties: false,
};
function validate22(
  data,
  {
    instancePath = '',
    parentData,
    parentDataProperty,
    rootData = data,
    dynamicAnchors = {},
  } = {},
) {
  let vErrors = null;
  let errors = 0;
  const evaluated0 = validate22.evaluated;
  if (evaluated0.dynamicProps) {
    evaluated0.props = undefined;
  }
  if (evaluated0.dynamicItems) {
    evaluated0.items = undefined;
  }
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0;
      if (
        (data.metadata === undefined && (missing0 = 'metadata')) ||
        (data.body === undefined && (missing0 = 'body')) ||
        (data.source_text === undefined && (missing0 = 'source_text'))
      ) {
        validate22.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ];
        return false;
      } else {
        const _errs1 = errors;
        for (const key0 in data) {
          if (
            !(key0 === 'metadata' || key0 === 'body' || key0 === 'source_text')
          ) {
            validate22.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ];
            return false;
            break;
          }
        }
        if (_errs1 === errors) {
          if (data.metadata !== undefined) {
            const _errs2 = errors;
            if (
              !validate21(data.metadata, {
                instancePath: instancePath + '/metadata',
                parentData: data,
                parentDataProperty: 'metadata',
                rootData,
                dynamicAnchors,
              })
            ) {
              vErrors =
                vErrors === null
                  ? validate21.errors
                  : vErrors.concat(validate21.errors);
              errors = vErrors.length;
            }
            var valid0 = _errs2 === errors;
          } else {
            var valid0 = true;
          }
          if (valid0) {
            if (data.body !== undefined) {
              let data1 = data.body;
              const _errs3 = errors;
              if (errors === _errs3) {
                if (typeof data1 === 'string') {
                  if (func1(data1) > 32768) {
                    validate22.errors = [
                      {
                        instancePath: instancePath + '/body',
                        schemaPath: '#/properties/body/maxLength',
                        keyword: 'maxLength',
                        params: { limit: 32768 },
                        message: 'must NOT have more than 32768 characters',
                      },
                    ];
                    return false;
                  }
                } else {
                  validate22.errors = [
                    {
                      instancePath: instancePath + '/body',
                      schemaPath: '#/properties/body/type',
                      keyword: 'type',
                      params: { type: 'string' },
                      message: 'must be string',
                    },
                  ];
                  return false;
                }
              }
              var valid0 = _errs3 === errors;
            } else {
              var valid0 = true;
            }
            if (valid0) {
              if (data.source_text !== undefined) {
                let data2 = data.source_text;
                const _errs5 = errors;
                if (errors === _errs5) {
                  if (typeof data2 === 'string') {
                    if (func1(data2) > 65536) {
                      validate22.errors = [
                        {
                          instancePath: instancePath + '/source_text',
                          schemaPath: '#/properties/source_text/maxLength',
                          keyword: 'maxLength',
                          params: { limit: 65536 },
                          message: 'must NOT have more than 65536 characters',
                        },
                      ];
                      return false;
                    }
                  } else {
                    validate22.errors = [
                      {
                        instancePath: instancePath + '/source_text',
                        schemaPath: '#/properties/source_text/type',
                        keyword: 'type',
                        params: { type: 'string' },
                        message: 'must be string',
                      },
                    ];
                    return false;
                  }
                }
                var valid0 = _errs5 === errors;
              } else {
                var valid0 = true;
              }
            }
          }
        }
      }
    } else {
      validate22.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ];
      return false;
    }
  }
  validate22.errors = vErrors;
  return errors === 0;
}
validate22.evaluated = {
  props: true,
  dynamicProps: false,
  dynamicItems: false,
};
export const validateSessionList = validate24;
const schema36 = {
  title: 'SessionList',
  type: 'object',
  properties: {
    items: {
      type: 'array',
      maxItems: 50,
      items: { $ref: '#/$defs/SessionMetadata' },
    },
    total: { type: 'integer', minimum: 0, maximum: 1000 },
    next_offset: { type: ['integer', 'null'], minimum: 0, maximum: 1000 },
  },
  required: ['items', 'total', 'next_offset'],
  additionalProperties: false,
};
function validate24(
  data,
  {
    instancePath = '',
    parentData,
    parentDataProperty,
    rootData = data,
    dynamicAnchors = {},
  } = {},
) {
  let vErrors = null;
  let errors = 0;
  const evaluated0 = validate24.evaluated;
  if (evaluated0.dynamicProps) {
    evaluated0.props = undefined;
  }
  if (evaluated0.dynamicItems) {
    evaluated0.items = undefined;
  }
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0;
      if (
        (data.items === undefined && (missing0 = 'items')) ||
        (data.total === undefined && (missing0 = 'total')) ||
        (data.next_offset === undefined && (missing0 = 'next_offset'))
      ) {
        validate24.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ];
        return false;
      } else {
        const _errs1 = errors;
        for (const key0 in data) {
          if (
            !(key0 === 'items' || key0 === 'total' || key0 === 'next_offset')
          ) {
            validate24.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ];
            return false;
            break;
          }
        }
        if (_errs1 === errors) {
          if (data.items !== undefined) {
            let data0 = data.items;
            const _errs2 = errors;
            if (errors === _errs2) {
              if (Array.isArray(data0)) {
                if (data0.length > 50) {
                  validate24.errors = [
                    {
                      instancePath: instancePath + '/items',
                      schemaPath: '#/properties/items/maxItems',
                      keyword: 'maxItems',
                      params: { limit: 50 },
                      message: 'must NOT have more than 50 items',
                    },
                  ];
                  return false;
                } else {
                  var valid1 = true;
                  const len0 = data0.length;
                  for (let i0 = 0; i0 < len0; i0++) {
                    const _errs4 = errors;
                    if (
                      !validate21(data0[i0], {
                        instancePath: instancePath + '/items/' + i0,
                        parentData: data0,
                        parentDataProperty: i0,
                        rootData,
                        dynamicAnchors,
                      })
                    ) {
                      vErrors =
                        vErrors === null
                          ? validate21.errors
                          : vErrors.concat(validate21.errors);
                      errors = vErrors.length;
                    }
                    var valid1 = _errs4 === errors;
                    if (!valid1) {
                      break;
                    }
                  }
                }
              } else {
                validate24.errors = [
                  {
                    instancePath: instancePath + '/items',
                    schemaPath: '#/properties/items/type',
                    keyword: 'type',
                    params: { type: 'array' },
                    message: 'must be array',
                  },
                ];
                return false;
              }
            }
            var valid0 = _errs2 === errors;
          } else {
            var valid0 = true;
          }
          if (valid0) {
            if (data.total !== undefined) {
              let data2 = data.total;
              const _errs5 = errors;
              if (
                !(
                  typeof data2 == 'number' &&
                  !(data2 % 1) &&
                  !isNaN(data2) &&
                  isFinite(data2)
                )
              ) {
                validate24.errors = [
                  {
                    instancePath: instancePath + '/total',
                    schemaPath: '#/properties/total/type',
                    keyword: 'type',
                    params: { type: 'integer' },
                    message: 'must be integer',
                  },
                ];
                return false;
              }
              if (errors === _errs5) {
                if (typeof data2 == 'number' && isFinite(data2)) {
                  if (data2 > 1000 || isNaN(data2)) {
                    validate24.errors = [
                      {
                        instancePath: instancePath + '/total',
                        schemaPath: '#/properties/total/maximum',
                        keyword: 'maximum',
                        params: { comparison: '<=', limit: 1000 },
                        message: 'must be <= 1000',
                      },
                    ];
                    return false;
                  } else {
                    if (data2 < 0 || isNaN(data2)) {
                      validate24.errors = [
                        {
                          instancePath: instancePath + '/total',
                          schemaPath: '#/properties/total/minimum',
                          keyword: 'minimum',
                          params: { comparison: '>=', limit: 0 },
                          message: 'must be >= 0',
                        },
                      ];
                      return false;
                    }
                  }
                }
              }
              var valid0 = _errs5 === errors;
            } else {
              var valid0 = true;
            }
            if (valid0) {
              if (data.next_offset !== undefined) {
                let data3 = data.next_offset;
                const _errs7 = errors;
                if (
                  !(
                    typeof data3 == 'number' &&
                    !(data3 % 1) &&
                    !isNaN(data3) &&
                    isFinite(data3)
                  ) &&
                  data3 !== null
                ) {
                  validate24.errors = [
                    {
                      instancePath: instancePath + '/next_offset',
                      schemaPath: '#/properties/next_offset/type',
                      keyword: 'type',
                      params: { type: schema36.properties.next_offset.type },
                      message: 'must be integer,null',
                    },
                  ];
                  return false;
                }
                if (errors === _errs7) {
                  if (typeof data3 == 'number' && isFinite(data3)) {
                    if (data3 > 1000 || isNaN(data3)) {
                      validate24.errors = [
                        {
                          instancePath: instancePath + '/next_offset',
                          schemaPath: '#/properties/next_offset/maximum',
                          keyword: 'maximum',
                          params: { comparison: '<=', limit: 1000 },
                          message: 'must be <= 1000',
                        },
                      ];
                      return false;
                    } else {
                      if (data3 < 0 || isNaN(data3)) {
                        validate24.errors = [
                          {
                            instancePath: instancePath + '/next_offset',
                            schemaPath: '#/properties/next_offset/minimum',
                            keyword: 'minimum',
                            params: { comparison: '>=', limit: 0 },
                            message: 'must be >= 0',
                          },
                        ];
                        return false;
                      }
                    }
                  }
                }
                var valid0 = _errs7 === errors;
              } else {
                var valid0 = true;
              }
            }
          }
        }
      }
    } else {
      validate24.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ];
      return false;
    }
  }
  validate24.errors = vErrors;
  return errors === 0;
}
validate24.evaluated = {
  props: true,
  dynamicProps: false,
  dynamicItems: false,
};
export const validateSessionCreated = validate26;
const schema37 = {
  title: 'SessionCreated',
  type: 'object',
  properties: { id: { $ref: '#/$defs/Identifier' } },
  required: ['id'],
  additionalProperties: false,
};
function validate26(
  data,
  {
    instancePath = '',
    parentData,
    parentDataProperty,
    rootData = data,
    dynamicAnchors = {},
  } = {},
) {
  let vErrors = null;
  let errors = 0;
  const evaluated0 = validate26.evaluated;
  if (evaluated0.dynamicProps) {
    evaluated0.props = undefined;
  }
  if (evaluated0.dynamicItems) {
    evaluated0.items = undefined;
  }
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0;
      if (data.id === undefined && (missing0 = 'id')) {
        validate26.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ];
        return false;
      } else {
        const _errs1 = errors;
        for (const key0 in data) {
          if (!(key0 === 'id')) {
            validate26.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ];
            return false;
            break;
          }
        }
        if (_errs1 === errors) {
          if (data.id !== undefined) {
            let data0 = data.id;
            const _errs3 = errors;
            if (errors === _errs3) {
              if (typeof data0 === 'string') {
                if (!pattern4.test(data0)) {
                  validate26.errors = [
                    {
                      instancePath: instancePath + '/id',
                      schemaPath: '#/$defs/Identifier/pattern',
                      keyword: 'pattern',
                      params: {
                        pattern:
                          '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
                      },
                      message:
                        'must match pattern "' +
                        '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' +
                        '"',
                    },
                  ];
                  return false;
                }
              } else {
                validate26.errors = [
                  {
                    instancePath: instancePath + '/id',
                    schemaPath: '#/$defs/Identifier/type',
                    keyword: 'type',
                    params: { type: 'string' },
                    message: 'must be string',
                  },
                ];
                return false;
              }
            }
          }
        }
      }
    } else {
      validate26.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ];
      return false;
    }
  }
  validate26.errors = vErrors;
  return errors === 0;
}
validate26.evaluated = {
  props: true,
  dynamicProps: false,
  dynamicItems: false,
};
export const validateVaultStatus = validate27;
const schema39 = {
  title: 'VaultStatus',
  type: 'object',
  properties: { connected: { type: 'boolean' }, ai_enabled: { const: false } },
  required: ['connected', 'ai_enabled'],
  additionalProperties: false,
};
function validate27(
  data,
  {
    instancePath = '',
    parentData,
    parentDataProperty,
    rootData = data,
    dynamicAnchors = {},
  } = {},
) {
  let vErrors = null;
  let errors = 0;
  const evaluated0 = validate27.evaluated;
  if (evaluated0.dynamicProps) {
    evaluated0.props = undefined;
  }
  if (evaluated0.dynamicItems) {
    evaluated0.items = undefined;
  }
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0;
      if (
        (data.connected === undefined && (missing0 = 'connected')) ||
        (data.ai_enabled === undefined && (missing0 = 'ai_enabled'))
      ) {
        validate27.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ];
        return false;
      } else {
        const _errs1 = errors;
        for (const key0 in data) {
          if (!(key0 === 'connected' || key0 === 'ai_enabled')) {
            validate27.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ];
            return false;
            break;
          }
        }
        if (_errs1 === errors) {
          if (data.connected !== undefined) {
            const _errs2 = errors;
            if (typeof data.connected !== 'boolean') {
              validate27.errors = [
                {
                  instancePath: instancePath + '/connected',
                  schemaPath: '#/properties/connected/type',
                  keyword: 'type',
                  params: { type: 'boolean' },
                  message: 'must be boolean',
                },
              ];
              return false;
            }
            var valid0 = _errs2 === errors;
          } else {
            var valid0 = true;
          }
          if (valid0) {
            if (data.ai_enabled !== undefined) {
              const _errs4 = errors;
              if (false !== data.ai_enabled) {
                validate27.errors = [
                  {
                    instancePath: instancePath + '/ai_enabled',
                    schemaPath: '#/properties/ai_enabled/const',
                    keyword: 'const',
                    params: { allowedValue: false },
                    message: 'must be equal to constant',
                  },
                ];
                return false;
              }
              var valid0 = _errs4 === errors;
            } else {
              var valid0 = true;
            }
          }
        }
      }
    } else {
      validate27.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ];
      return false;
    }
  }
  validate27.errors = vErrors;
  return errors === 0;
}
validate27.evaluated = {
  props: true,
  dynamicProps: false,
  dynamicItems: false,
};
